### PR TITLE
SKColor updates fix and tests

### PR DESCRIPTION
**Pull request by maxgribov**
fixes bug #50

### CODE REVIEW

**Comment by sy522188988** [comment]
I still have errors after updating

**Comment by sy522188988** [comment]
"slots":  {
"eyesHappyleft_2":  {
"rgba":  [
 {
"time": 0.3 ,
"color": "ffffff00"
},
 {
"time": 0.3333 ,
"color": "ffffffff" ,
"curve": "stepped"
},
 {
"time": 1.3667 ,
"color": "ffffffff"
},
 {
"time": 1.4 ,
"color": "ffffff00"
}
]
}The opacity changes in a given frame, but now the image is always there

**Comment by maxgribov** [comment]
You changing the opacity of the color that multiplied to an image. The transparency of the image should not change.

**Comment by sy522188988** [comment]
[actor_base.txt](https://github.com/maxgribov/Spine/files/11528646/actor_base.txt)

**Comment by sy522188988** [comment]
https://github.com/maxgribov/Spine/assets/20471877/cd7095f7-1a3c-4e38-90d4-7174615c24b3

So this is the spine after I loaded it up and it obviously has a problem

**Pull request merged**
